# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com


readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true
  
# Build settings
markdown: kramdown
kramdown:
  math_engine: katex  # 我加了这个才能显示 latex 数学公式

# permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-readme-index

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: '_posts'
    values:
      permalink: /posts/:path:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
